### ISSUE TITLE
建議捨棄 wiki，直接把內容寫在 repo 

### ISSUE THREAD

**Issue by chchwy** [taiwanese-work-in/australia#1]
wiki 管理不太方便，而且不能接受 pull request 。導致想提供內容的人都必須要有寫入權限，這樣不好管理。

Github 的 README 是可以支援超連結的
https://help.github.com/articles/relative-links-in-readmes/

建議捨棄 wiki，直接把文章內容寫在 repo 內，把 README.md 當作入口就好。

**Comment by yorkxin** [comment]
Wiki 的編輯權限是公開的，您應該可以直接編輯？

**Comment by chchwy** [comment]
我的問題不是「能不能直接編輯」，而是作為一個內容管理工具，Git Repo 本身其實比 Github Wiki 更有威力，有可以追蹤內容修改，可以 clone/fork，可以透過 pull request 審查，也可以寫 markdown。

反觀 Github Wiki 只能算是一個簡便的方案。

**Comment by ascendbruce** [comment]
同意 Git repo 可以比 wiki 更有威力，但如果連簡便的方案都沒有辦法讓內容從缺乏變成中等數量，老實說我不認為採取稍微麻煩一點的方案可以讓內容更臻完美

@chchwy 是否考慮先用 wiki 編輯，若真的過程中出現太多問題非切換至 repo 不可，我們再轉移也不遲？

**Comment by wayne5540** [comment]
蠻意外目前已經有一些 wiki contributors 了, 就先暫時保持這個做法吧，讓編輯越簡單越好，以後資訊量大起來可以再看看怎麼改進～謝啦：）
