### ISSUE TITLE
建議 wiki 部分頁面重新命名以改善關鍵字能見度

### ISSUE THREAD

**Issue by ascendbruce** [taiwanese-work-in/australia#2]
## Why is this change necessary
- For SEO
## Proposed solution
- 關於薪水 => 澳洲薪水與稅金
- 過來人經歷 => 澳洲工作過來人經歷
- 台灣社群 => 台灣人在澳洲社群
- ...等等

若擔心 404 問題，可考慮暫時把舊的頁面留下來放網址，但考慮到目前每日 unique users 不超過 5 人，或許還不必顧慮這麼多

**Comment by yorkxin** [comment]
如果只是改名字的話好像會 redirect

**Comment by wayne5540** [comment]
@ascendbruce 恐怕每日 unique users 的 80% 都是爬蟲吧哈哈哈ＸＤ 不考慮這麼多了就直接改囉～

**Comment by ascendbruce** [comment]
> 如果只是改名字的話好像會 redirect

看來 wiki page 不會，例： https://github.com/taiwanese-work-in/australia/wiki/%E9%97%9C%E6%96%BC%E8%96%AA%E6%B0%B4

未登入狀況下會被 redirect 到 wiki 首頁
